In [1]:
import numpy as np

In [3]:
adj_closings_sbra = np.loadtxt("SBRA.csv", skiprows=1, usecols=5, delimiter=',')
print(adj_closings_sbra)

[15.36233  16.012386 16.528606 16.882313 17.427212 17.522808 17.513248
 17.427212 17.264698 17.417652 17.847836 18.105947 18.344938 18.306698
 18.497892 18.77512  19.09059  19.386936 19.377378 19.55901  19.635489
 19.425177 19.664167 19.539892 19.635489 19.80756  19.654606 19.60681
 19.358257 19.32958  19.339357 19.544678 19.388243 19.241585 19.222029
 19.143812 18.635395 18.381187 18.038986 17.716337 17.31547  17.247028
 17.256807 17.149258 17.119926 17.071039 17.383911 17.608788 17.941214
 17.970543 17.892326 17.726112 17.765223 17.980322 18.58651  18.293192
 18.449629 18.762501 18.870049 19.192698 19.036261 18.899382 18.879826
 18.694059 18.762501 18.958044 18.870049 18.801609 19.04604  19.241585
 19.241585 19.222029 18.821163 18.361633 18.713614 18.410519 18.713614
 18.909159 18.909159 19.153589 18.967821 19.124256 19.094927 19.143812
 19.554455 19.456682 19.143812 19.319801 18.840717 19.310024 19.241585
 19.417574 19.574011 19.75     19.709999 19.530001 19.73     19.700001
 19.709

In [4]:
adj_closings_eqr=np.loadtxt("EQR.csv", skiprows=1, usecols=5, delimiter=',')
print(adj_closings_eqr)

[62.800674 63.19466  63.588642 64.120514 65.322166 65.322166 66.395767
 66.533653 66.61245  67.429955 68.040634 68.858147 69.064987 69.340775
 69.28167  69.291527 69.606705 70.640915 71.281136 70.916695 71.468269
 70.936401 71.694817 71.852402 71.901649 72.433533 72.335037 72.354729
 71.448578 72.187286 72.019852 72.10849  72.423676 71.586472 72.748718
 73.113152 72.394127 72.610817 72.226692 72.581276 72.394127 72.866913
 72.817657 72.443382 72.325188 72.532021 73.319992 73.920807 73.782921
 73.930656 73.635178 72.866913 72.394127 72.512329 73.664719 73.841385
 73.910858 74.575829 74.41703  75.062149 74.754478 74.41703  75.121704
 74.823952 74.714775 75.042297 74.992676 74.823952 75.776741 76.114189
 76.868484 77.017357 75.1614   73.732208 74.506355 73.613106 74.397179
 74.903351 75.399597 75.627869 74.734627 75.846214 75.945465 75.82637
 76.014938 75.637794 74.208603 73.881088 74.258232 75.260651 75.270569
 75.240791 75.61795  76.233284 76.044716 75.181252 75.786667 76.064568
 76.531

In [5]:
def simple_rate_of_return(adj_closings): 
  daily_simple_ror = np.diff(adj_closings)/adj_closings[:1]
  return daily_simple_ror

In [6]:
daily_simple_returns_sbra = simple_rate_of_return(adj_closings_sbra)
daily_simple_returns_sbra

array([ 0.04231494,  0.03360298,  0.02302431,  0.03546981,  0.00622275,
       -0.0006223 , -0.00560045, -0.01057873,  0.00995643,  0.02800252,
        0.01680155,  0.01555695, -0.00248921,  0.01244564,  0.01804596,
        0.0205353 ,  0.01929043, -0.00062217,  0.01182321,  0.00497835,
       -0.01369011,  0.01555688, -0.00808959,  0.00622282,  0.01120084,
       -0.00995643, -0.00311125, -0.01617938, -0.00186671,  0.00063643,
        0.01336523, -0.01018303, -0.0095466 , -0.00127298, -0.00509148,
       -0.03309504, -0.01654749, -0.02227533, -0.02100261, -0.02609415,
       -0.00445518,  0.00063656, -0.00700083, -0.00190935, -0.00318226,
        0.02036618,  0.01463821,  0.02163904,  0.00190915, -0.00509148,
       -0.01081958,  0.0025459 ,  0.01400172,  0.03945938, -0.01909333,
        0.01018316,  0.02036618,  0.00700076,  0.02100261, -0.01018316,
       -0.00891004, -0.00127298, -0.01209237,  0.00445518,  0.01272873,
       -0.00572797, -0.00445505,  0.01591106,  0.01272886,  0.  

In [7]:
average_daily_simple_return_sbra = np.mean(daily_simple_returns_sbra)
average_daily_simple_return_sbra

0.0022902982212444803

In [8]:
def log_returns(adj_closings):
    log_adj_closings = np.log(adj_closings)
    daily_log_returns = np.diff(log_adj_closings)
    return daily_log_returns

In [9]:
daily_log_returns_sbra = log_returns(adj_closings_sbra)
daily_log_returns_sbra 

array([ 0.04144414,  0.03173003,  0.02117393,  0.03176639,  0.00547045,
       -0.00054572, -0.00492473, -0.00936905,  0.00882034,  0.02439809,
        0.01435818,  0.01311323, -0.00208667,  0.01038978,  0.01487581,
        0.01666295,  0.01540389, -0.00049313,  0.00932975,  0.00390254,
       -0.01076858,  0.01222804, -0.00633993,  0.00488047,  0.00872509,
       -0.00775197, -0.00243476, -0.01275791, -0.00148248,  0.00050568,
        0.01056078, -0.00803617, -0.00759303, -0.00101686, -0.00407743,
       -0.0269168 , -0.01373503, -0.01879239, -0.0180481 , -0.02288689,
       -0.00396048,  0.00056684, -0.00625177, -0.00171186, -0.00285965,
        0.01816172,  0.01285297,  0.01870243,  0.00163339, -0.00436201,
       -0.0093331 ,  0.00220398,  0.01203516,  0.03315811, -0.01590708,
        0.00851529,  0.01681599,  0.00571571,  0.01695394, -0.00818426,
       -0.00721641, -0.00103528, -0.00988817,  0.00365448,  0.01036808,
       -0.00465237, -0.0036335 ,  0.01291675,  0.01021462,  0.  

In [10]:
def annualize_log_return(daily_log_returns):
  average_daily_log_returns = np.mean(daily_log_returns)
  annualized_log_return = average_daily_log_returns * 250
  return annualized_log_return

In [11]:
annualized_log_return_sbra = annualize_log_return(daily_log_returns_sbra)
print(annualized_log_return_sbra)

0.5044563709645333


In [12]:
#Calculate Variance of Daily log returns 
daily_variance_sbra = np.var(daily_log_returns_sbra)
daily_variance_sbra

0.00017844226355047074

In [13]:
#Calculate Standard Deviation
daily_sd_sbra = np.std(daily_log_returns_sbra)

In [14]:
#Calculate Simple Rate of Return EQR
daily_simple_returns_eqr = simple_rate_of_return(adj_closings_eqr)
print(daily_simple_returns_eqr)

[ 0.0062736   0.00627353  0.00846921  0.01913438  0.          0.01709537
  0.00219561  0.00125472  0.01301746  0.00972408  0.01301758  0.0032936
  0.00439148 -0.00094115  0.00015696  0.0050187   0.01646814  0.01019449
 -0.00580314  0.00878293 -0.00846914  0.01207656  0.00250929  0.00078418
  0.0084694  -0.00156839  0.00031356 -0.014429    0.01176274 -0.00266612
  0.00141142  0.00501883 -0.01333113  0.0185069   0.00580303 -0.01144932
  0.00345044 -0.00611657  0.00564618 -0.00298005  0.00752836 -0.00078432
 -0.00595973 -0.00188205  0.00329348  0.01254717  0.00956702 -0.00219561
  0.00235244 -0.00470501 -0.01223339 -0.00752836  0.00188218  0.01834996
  0.00281312  0.00110625  0.0105886  -0.00252862  0.01027249 -0.00489917
 -0.00537332  0.0112208  -0.00474122 -0.00173847  0.00521526 -0.00079013
 -0.00268666  0.01517164  0.00537332  0.01201094  0.00237056 -0.02955314
 -0.02275759  0.01232705 -0.01422356  0.0124851   0.00805998  0.00790192
  0.00363487 -0.01422345  0.01770024  0.00158041 -0.

In [15]:
#Calculate Average Daily Return EQR
average_daily_simple_return_eqr = np.mean(daily_simple_returns_eqr)
print(average_daily_simple_return_eqr)

0.0016984080573993103


In [16]:
#Calculate Daily Log Returns EQR
daily_log_returns_eqr = log_returns(adj_closings_eqr)
print(daily_log_returns_eqr)

[ 0.006254    0.00621507  0.00832947  0.01856708  0.          0.01630188
  0.00207458  0.00118362  0.01219786  0.00901573  0.01194346  0.00299935
  0.00398522 -0.00085275  0.00014226  0.00453827  0.01474861  0.00902221
 -0.00512584  0.00774768 -0.00746985  0.01063474  0.00219559  0.00068516
  0.00737016 -0.00136074  0.0002722  -0.01260281  0.01028593 -0.00232213
  0.00122999  0.00436147 -0.01162714  0.01610517  0.00499698 -0.00988309
  0.00298873 -0.00530423  0.00489731 -0.0025818   0.00650949 -0.0006762
 -0.00515315 -0.00163287  0.00285568  0.01080518  0.00816103 -0.00186706
  0.00200029 -0.0040047  -0.01048821 -0.00650949  0.00163143  0.01576737
  0.00239537  0.0009404   0.0089567  -0.00213163  0.00863161 -0.00410731
 -0.0045243   0.0094247  -0.00397147 -0.00146018  0.00437405 -0.00066146
 -0.00225241  0.01265335  0.0044433   0.00986126  0.00193485 -0.02439301
 -0.01919808  0.01044471 -0.01206134  0.01059494  0.0067806   0.0066033
  0.00302292 -0.01188132  0.01476426  0.00130773 -0.0

In [17]:
#Calculate Annualize Daily Log Return EQR
annualized_log_return_eqr = annualize_log_return(daily_log_returns_eqr)
print(annualized_log_return_eqr)

0.3855982155640554


In [18]:
#Calculate Variance of Daily Log Returns EQR
daily_varaince_eqr = np.var(daily_log_returns_eqr)
print(daily_varaince_eqr)

6.833881310511606e-05


In [19]:
# Calculate Daily Standard Deviation EQR
daily_sd_eqr = np.std(daily_log_returns_eqr)
print(daily_sd_eqr)

0.00826672928703463


In [21]:
#Calculate the Correlation between SBRA and EQR

corr_sbra_eqr = np.corrcoef(daily_log_returns_sbra, daily_log_returns_eqr)
corr_sbra_eqr

  

array([[1.        , 0.62096591],
       [0.62096591, 1.        ]])